/**
 * AgroMarket Phase 2.0: Canonical Value-Chain Stage Templates
 * Pure definitions for interactive value-chain discovery across crops, livestock, aquaculture, and dairy.
 */

import { ValueChainTemplate } from "./types";

export function getCanonicalValueChainTemplates(): ValueChainTemplate[] {
  return [
    {
      id: "vc-poultry",
      name: "Broiler Poultry Value Chain",
      category: "LIVESTOCK",
      commodity: "Broiler Chicken",
      summary:
        "Coordinated commercial broiler lifecycle from hatchery breeding, farm brooding, aggregation, specialized abattoir slaughter/dressing, cold-chain transport, and institutional market delivery.",
      stages: [
        {
          id: "p1",
          label: "Breeding & Brooding",
          description: "Day-old chicks (DOC) raised in temperature-controlled poultry units.",
          actorRole: "Farmer / Production Unit",
          keyOutputs: ["Live Broiler Birds (6-8 weeks, 1.8-2.5kg)"],
          status: "COMPLETED",
        },
        {
          id: "p2",
          label: "Supply Aggregation",
          description: "Coordinating batch collections from smallholders into pooled volume.",
          actorRole: "Aggregator / Cooperative",
          keyOutputs: ["Aggregated Harvest Pool (1,000+ birds)"],
          status: "CURRENT",
        },
        {
          id: "p3",
          label: "Halal Abattoir Processing",
          description: "Stun-free halal slaughtering, defeathering, dressing, and portioning.",
          actorRole: "Poultry Processor",
          keyOutputs: ["Whole Dressed Birds", "Portioned Cuts (Wings, Breasts, Drumsticks)"],
          status: "UPCOMING",
        },
        {
          id: "p4",
          label: "Blast Freezing & Packaging",
          description: "Food-grade vacuum packaging, blast freezing (-18°C), and barcode batch labeling.",
          actorRole: "Packaging / Cold-Chain Provider",
          keyOutputs: ["Blast-Frozen Cartons (10kg / 20kg)"],
          status: "UPCOMING",
        },
        {
          id: "p5",
          label: "Refrigerated Logistics",
          description: "Third-party refrigerated reefer delivery to urban distribution hubs.",
          actorRole: "Logistics Provider",
          keyOutputs: ["Cold Corridor Transit", "Verified Temperature Records"],
          status: "UPCOMING",
        },
        {
          id: "p6",
          label: "Commercial & Retail Markets",
          description: "Offtake fulfillment to restaurants, hotels, supermarkets, and B2B buyers.",
          actorRole: "Wholesaler / Restaurant / Buyer",
          keyOutputs: ["Fulfilled B2B Demand", "Consumer Deliveries"],
          status: "UPCOMING",
        },
      ],
    },
    {
      id: "vc-cattle",
      name: "Cattle & Beef Value Chain",
      category: "LIVESTOCK",
      commodity: "Beef Cattle",
      summary:
        "Coordinated pastoral and feedlot beef coordination across northern grazing states to central abattoirs, carcass dressing, and cold delivery to southern consumer demand centers.",
      stages: [
        {
          id: "c1",
          label: "Feedlot & Pastoral Rearing",
          description: "White Fulani / Sokoto Gudali raised to maturity with veterinary oversight.",
          actorRole: "Rancher / Farmer / Pastoralist",
          keyOutputs: ["Live Prime Cattle (300-450kg)"],
          status: "COMPLETED",
        },
        {
          id: "c2",
          label: "Livestock Aggregation",
          description: "Consolidated assembly at regional livestock terminals (e.g. Dawanau, Wudil, Potiskum).",
          actorRole: "Livestock Aggregator / Market Operator",
          keyOutputs: ["Batch Manifest", "Veterinary Waybill"],
          status: "CURRENT",
        },
        {
          id: "c3",
          label: "Interstate Transit",
          description: "Vetted livestock transport via north-south transit corridors.",
          actorRole: "Third-Party Logistics Provider",
          keyOutputs: ["Dispatched Consignment", "Transit Event Log"],
          status: "UPCOMING",
        },
        {
          id: "c4",
          label: "Regulated Abattoir Slaughter",
          description: "Humane, halal-inspected slaughtering, skinning, and veterinary ante-mortem inspection.",
          actorRole: "Abattoir / Meat Processor",
          keyOutputs: ["Dressed Beef Carcass", "Hides / By-products"],
          status: "UPCOMING",
        },
        {
          id: "c5",
          label: "Butchering & Cold Distribution",
          description: "Chilled quartering, portioning, vacuum packing, and cold-van retail distribution.",
          actorRole: "Cold Chain / Distributor",
          keyOutputs: ["Prime Beef Cuts", "Minced Beef Cartons"],
          status: "UPCOMING",
        },
        {
          id: "c6",
          label: "B2B & Retail Markets",
          description: "Supply to hotel chains, institutional caterers, and butcher networks.",
          actorRole: "Institutional Buyer / Retailer",
          keyOutputs: ["Market Deliveries", "Verified Quality Acceptance"],
          status: "UPCOMING",
        },
      ],
    },
    {
      id: "vc-catfish",
      name: "Aquaculture & Catfish Value Chain",
      category: "AQUACULTURE",
      commodity: "African Catfish (Clarias)",
      summary:
        "Ecosystem flow from earthen/tarpaulin pond grow-out, harvest grading, artisanal smoking or blast-freezing, vacuum preservation, and restaurant delivery.",
      stages: [
        {
          id: "f1",
          label: "Hatchery & Pond Grow-out",
          description: "Fingerlings nurtured in biosecure earthen or concrete ponds for 4-5 months.",
          actorRole: "Fish Farmer / Aquaculture Unit",
          keyOutputs: ["Live Table-Size Catfish (1.0kg - 1.5kg)"],
          status: "COMPLETED",
        },
        {
          id: "f2",
          label: "Harvest Batch Pooling",
          description: "Grading and sorting into live haulage tanks or processing batches.",
          actorRole: "Aggregator / Aquaculture Cluster",
          keyOutputs: ["Graded Catch Batch (500kg+)"],
          status: "CURRENT",
        },
        {
          id: "f3",
          label: "Kiln Smoking or Chilling",
          description: "Hygienic oven-smoking or fresh gutting and icing.",
          actorRole: "Fish Processor",
          keyOutputs: ["Oven-Dried Smoked Catfish", "Chilled Gutted Fish"],
          status: "UPCOMING",
        },
        {
          id: "f4",
          label: "Moisture-Barrier Packaging",
          description: "Heat-sealed food grade pouches preserving shelf life up to 6 months.",
          actorRole: "Packaging Provider",
          keyOutputs: ["Export-Grade Packaged Catfish"],
          status: "UPCOMING",
        },
        {
          id: "f5",
          label: "Hub Logistics",
          description: "Consolidated dispatch to supermarkets and interstate distributors.",
          actorRole: "Logistics Carrier",
          keyOutputs: ["Consignment Delivery", "Chain-of-Custody Tracking"],
          status: "UPCOMING",
        },
        {
          id: "f6",
          label: "Retail & Hospitality Offtake",
          description: "Direct offtake by pepper soup restaurants, hotels, and retail shoppers.",
          actorRole: "Restaurant / Retailer / Consumer",
          keyOutputs: ["Settled Commercial Order"],
          status: "UPCOMING",
        },
      ],
    },
    {
      id: "vc-cassava",
      name: "Cassava & Garri Value Chain",
      category: "CROP",
      commodity: "Cassava Tubers",
      summary:
        "High-volume staple crop value chain from rain-fed smallholder harvesting, cooperative aggregation, automated peeling and grating, fermentation, roasting into Garri, and bulk distribution.",
      stages: [
        {
          id: "cs1",
          label: "Farm Cultivation & Harvest",
          description: "Matured vitamin-A or white cassava harvested within 24-48h processing window.",
          actorRole: "Crop Farmer / Production Unit",
          keyOutputs: ["Fresh Cassava Tubers (Tons)"],
          status: "COMPLETED",
        },
        {
          id: "cs2",
          label: "Cooperative Aggregation",
          description: "Rapid collection at village farm gates to avoid post-harvest root deterioration.",
          actorRole: "Aggregator / Cooperative",
          keyOutputs: ["Consolidated Truckload (10-30 Metric Tons)"],
          status: "CURRENT",
        },
        {
          id: "cs3",
          label: "Industrial Milling & Roasting",
          description: "Mechanical peeling, washing, grating, hydraulic dewatering, and automated fryers.",
          actorRole: "Crop Processor / Garri Mill",
          keyOutputs: ["Dry Roasted Garri (Ijebu / Yellow)", "High-Quality Cassava Flour (HQCF)"],
          status: "UPCOMING",
        },
        {
          id: "cs4",
          label: "Standardized Bagging",
          description: "Woven polypropylene 50kg and 100kg branded bags with moisture liners.",
          actorRole: "Packaging Provider",
          keyOutputs: ["50kg Sealed Garri Bags", "Retail 5kg Packs"],
          status: "UPCOMING",
        },
        {
          id: "cs5",
          label: "Wholesale Freight Transit",
          description: "Haulage from farm belt (Ogun, Oyo, Edo, Benue) to metropolitan staple markets.",
          actorRole: "Third-Party Logistics Provider",
          keyOutputs: ["Market Consignments"],
          status: "UPCOMING",
        },
        {
          id: "cs6",
          label: "Metropolitan Market Offtake",
          description: "Sale in major terminal food markets (Mile 12, Bodija) and B2B supermarket chains.",
          actorRole: "Wholesaler / Market Operator",
          keyOutputs: ["Completed B2B Wholesale Delivery"],
          status: "UPCOMING",
        },
      ],
    },
    {
      id: "vc-dairy",
      name: "Fresh Milk & Dairy Value Chain",
      category: "DAIRY",
      commodity: "Cow Milk",
      summary:
        "Cold-chain coordinated milk collection from local dairy pastoralists, chilled aggregation centers, quality lactometer testing, pasteurization, and consumer yoghurt/cheese packaging.",
      stages: [
        {
          id: "d1",
          label: "Dairy Milking & Collection",
          description: "Morning milking under sanitary protocols with immediate aluminum can storage.",
          actorRole: "Dairy Farmer / Pastoralist",
          keyOutputs: ["Raw Bovine Milk (Liters)"],
          status: "COMPLETED",
        },
        {
          id: "d2",
          label: "Milk Collection Center (MCC)",
          description: "Rapid chilling to 4°C within 2 hours, fat/solids lactometer verification.",
          actorRole: "Aggregator / Dairy Cooperative",
          keyOutputs: ["Chilled Bulk Milk Tankers"],
          status: "CURRENT",
        },
        {
          id: "d3",
          label: "Pasteurization & Processing",
          description: "High-temperature short-time (HTST) pasteurization, homogenization, culturing.",
          actorRole: "Dairy Processor",
          keyOutputs: ["Pasteurized Fresh Milk", "Probiotic Yoghurt", "Wara (Fresh Cheese)"],
          status: "UPCOMING",
        },
        {
          id: "d4",
          label: "Aseptic Packaging",
          description: "Hermetically sealed bottles and cartons with expiration date stamping.",
          actorRole: "Packaging Facility",
          keyOutputs: ["Bottled Yoghurt (500ml)", "Milk Cartons (1L)"],
          status: "UPCOMING",
        },
        {
          id: "d5",
          label: "Reefer Cold Chain",
          description: "Continuous 2°C - 4°C temperature log transit to retail cold rooms.",
          actorRole: "Cold-Chain Logistics Provider",
          keyOutputs: ["Audited Temperature Log Transits"],
          status: "UPCOMING",
        },
        {
          id: "d6",
          label: "Institutional & Grocery Retail",
          description: "Supply to school feeding programs, hotels, cafes, and supermarkets.",
          actorRole: "Institutional Buyer / Retailer",
          keyOutputs: ["Delivered Dairy Orders"],
          status: "UPCOMING",
        },
      ],
    },
  ];
}
